server:  
  port: 8212
  
spring:
  application:    
    name: gatewayservice
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

zuul:
  routes:    
    eureka:
      path: /eureka/**
      url: http://localhost:8761/
    data:
      path: /data/**
      service-id: dataservice
    reports:
      path: /reports/**
      service-id: reportsservice