#EUREKA MASTER PORT IS 2329 - SWAP THIS IN WHEN PUSHING TO MASTER
#EUREKA DEVELOPMENT PORT IS 8762 - THIS SHOULD BE ACTIVE BY DEFAULT

spring:
  application:
    name: registryservice
server:
  port: 8762

#  Eureka Config
eureka:
  server:
    enable-self-preservation: false
  client:
    fetch-registry: false
    register-with-eureka: false

        
##OLD FILE BELOW. DELETE LATER IF THIS ALL WORKS
##EUREKA MASTER PORT IS 2329 - SWAP THIS IN WHEN PUSHING TO MASTER
##EUREKA DEVELOPMENT PORT IS 8762 - THIS SHOULD BE ACTIVE BY DEFAULT
#
#spring.application.name=registryservice
#server.port=8762
#
#
#eureka.server.enable-self-preservation=false
#eureka.client.fetch-registry=false
#eureka.client.register-with-eureka=false